Enhancement/input field masking date 1211
kirbydesign/designsystem pull request #1430
Opened 2021-03-19 16:58 UTC by karlgodtliebsen

This PR closes # 1211

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
Enhancement

What kind of change does this PR introduce?
Input filter/masking for Date Input and Icon

- [ ] Bugfix
- [ ] Feature
- [x ] Enhancement (to existing content)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## Which issue documents the current behaviour?

https://github.com/kirbydesign/designsystem/issues/1211

Issue Number: #1211 

## What is the new behavior?
Mask on Date Inputs and ability to enable a Date icon which Show Calendar

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## Other information

2021-04-08 11:27 UTC, flemcito requested changes
Good work. I like the directive approach as it keeps the api as simple as possible.
I have mainly comments regarding code structure/readability

2021-04-08 11:27 UTC, flemcito commented on libs/designsystem/src/lib/components/form-field/directives/date/date-mask.service.ts
> +  private getDateFormatOrder(localeDateFormat: string): DateFormatOrder {
Maybe do something like this? 
```suggestion
  private getDateFormatOrder(): DateFormatOrder {
    const localeDateFormat = getLocaleDateFormat(
      this.locale,
      FormatWidth.Short
    ).toLocaleLowerCase();

    return [...new Set(localeDateFormat.match(/([dmy])/g))] as DateFormatOrder;
  }
```

2021-04-08 11:27 UTC, flemcito commented on libs/designsystem/src/lib/components/form-field/directives/date/date-mask.service.ts
> +  // TODO: ADD TESTS
Remove TODO (or add tests) :)

2021-04-08 11:27 UTC, flemcito commented on libs/designsystem/src/lib/components/form-field/input/input.component.scss
> +  // TODO: use another selector
Remove TODO.
Would it be an option to add class?

2021-04-08 11:27 UTC, flemcito commented on libs/designsystem/src/lib/scss/_global-styles.scss
> +  padding: 16px;
Magic numbers. Better to use size variables

2021-04-13 06:37 UTC, hafstad commented
Closing this pull-req in favor of #1461, so deployment works

2021-04-13 06:37 UTC, closed without merging