Enhancement/alert decoration on top
kirbydesign/designsystem pull request #1448
Opened 2021-03-31 14:30 UTC by RasmusKjeldgaard

This PR closes #968 
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Enhancement (to existing content)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## Which issue documents the current behaviour?

Issue Number: #968 

## What is the new behavior?

If there is an icon in the alert, it is now above the title. 

To do this, the alert now passes on its title to the already existing title-implementation in the empty-state component. 
To reuse the empty-state component, some context-specific styling needed to be added, so the alerts without icons keep their current look, and the margins are reduced when an icon is present. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-03-31 14:33 UTC, RasmusKjeldgaard commented
I still need to add some tests to watch for regressions (especially because the css rules I added are rather specific, so if e.g. the class icon-outline class is renamed, it will render differently), but would love a sanity check to see if this is the way to go.

2021-04-06 18:57 UTC, jakobe requested changes

2021-04-06 18:57 UTC, jakobe commented on libs/designsystem/src/lib/components/modal/alert/alert.component.html
> +    [title]="title$ | async"
Consider readability:
```suggestion
    [title]="title$ | async"
    [subtitle]="message$ | async"
```

2021-04-06 18:57 UTC, jakobe commented on libs/designsystem/src/lib/components/modal/alert/alert.component.scss
> +  padding: size('m') size('s') size('s');
Consider readability:
```suggestion
  padding: size('s');
  padding-top: size('m');
```

2021-04-07 06:53 UTC, jakobe approved these changes

2021-04-07 07:42 UTC, merged