Enhancement/output active slide index
kirbydesign/designsystem pull request #1458
Opened 2021-04-09 09:32 UTC by MonsterGameDev

This PR closes # (reference issue number here)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Enhancement (to existing content)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## Which issue documents the current behaviour?

Issue Number: #[replace with issue number]

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-04-16 07:35 UTC, jakobe requested changes

2021-04-16 07:35 UTC, jakobe commented on .vscode/settings.json
> +{
Please remove 🔥

2021-04-16 08:31 UTC, MonsterGameDev commented on .vscode/settings.json
> +{
? hvordan f..... er den kommet med. jeg hiver den ud. Sorry :-/

2021-04-16 09:20 UTC, MonsterGameDev commented on .vscode/settings.json
> +{
Den står højt og flot i min git-ignore fil. Men jeg skulle selvfølgelig have checket files-changed. Wont happen again

2021-04-21 10:06 UTC, jakobe approved these changes

2021-04-21 10:18 UTC, merged