Create cookbook example page(s) for grid layout
kirbydesign/designsystem pull request #1676
Opened 2021-07-09 14:08 UTC by jkaltoft

## Which issue does this PR close?

This PR closes #1668

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](./CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

2021-07-14 10:44 UTC, RasmusKjeldgaard requested changes
Really great examples of grid usage. Will be even more awesome combined with a showcase down the line!

2021-07-15 09:52 UTC, RasmusKjeldgaard approved these changes
LGTM... Because I made the changes!

2021-07-15 10:26 UTC, MadsBuchmann approved these changes
Ship it! 

![](https://media3.giphy.com/media/h4NlRPJCQAXOto7E4g/giphy.gif?cid=ecf05e478c6j08skoounu9zgxvm9d6r1fo6mqq5bpmq0ik8b&rid=giphy.gif&ct=g)

2021-07-15 10:26 UTC, MadsBuchmann commented on apps/cookbook/src/app/examples/grid-layout-example/grid-layout-core-example/grid-layout-core-example.component.scss
>  $columns: 12;
We could consider if we should have specific design tokens for grid in `_variables.scss`. 

But perhaps this should be talked more over and a new issue should be created for this

2021-07-15 10:28 UTC, merged