Fix default HTML list styles
kirbydesign/designsystem pull request #1850
Opened 2021-10-29 14:24 UTC by jkaltoft

## Which issue does this PR close?

This PR closes #1802 

## What is the new behavior?

This PR replaces what was reverted in #1807.

Kirby applies default styles to HTML lists that differ a bit from user agent styles.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

It may be necessary to adjust list styles where the new defaults are not wanted. Every HTML list will need to be checked individually.

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

2021-11-02 11:49 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/styling-list-example/styling-list-example.component.html
> +<h2>Unordered List Example</h2>
Consider wrapping each of these examples in a card like we do for https://cookbook.kirby.design/#/home/showcase/badge, to separate them a little more

2021-11-04 15:39 UTC, RasmusKjeldgaard requested changes
This seems like a really solid solution. I only have some comments for how it is presented in the cookbook.

Really great work, and a testament to relying on the browser/spec as much as possible!

2021-11-04 15:39 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/styling-list-example/styling-list-example.component.html
> +<h2>Unordered List Example</h2>
We could also consider to make a 2 column layout for these examples, in addition to the above stuff.

2021-11-04 15:39 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/examples.routes.ts
> +    path: 'styling-list',
Should we name this 'Styling HTML Lists' so it is a little more specific when it shows up in the cookbook menu?

2021-11-22 11:17 UTC, RasmusKjeldgaard reviewed
Refresh my memory - why are we merging this to release/next when there are no breaking changes in this variant of the solution? 

Otherwise, everything looks good!

2021-11-29 13:22 UTC, jkaltoft commented
> Refresh my memory - why are we merging this to release/next when there are no breaking changes in this variant of the solution?
> 
> Otherwise, everything looks good!

My memory needs to be refreshed, too 😁. I'll look into it, but I think it still _is_ breaking.

2021-11-29 14:51 UTC, jkaltoft commented
> > Refresh my memory - why are we merging this to release/next when there are no breaking changes in this variant of the solution?
> > Otherwise, everything looks good!
> 
> My memory needs to be refreshed, too 😁. I'll look into it, but I think it still _is_ breaking.

Ok, it _is_ breaking. Very, very little, but still, consumer apps should check every occurrence of unordered/ordered lists, e.g., the main menu in relationsbanken.

2021-11-29 15:22 UTC, RasmusKjeldgaard approved these changes

2021-11-29 15:26 UTC, merged