Added subtitle concept to page component
kirbydesign/designsystem pull request #2030
Opened 2022-02-02 11:34 UTC by mictro

## Which issue does this PR close?

This PR closes # (insert issue number here)

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

2022-03-03 10:38 UTC, MadsBuchmann requested changes
Got some questions and request for changes. Mostly nitpicky stuff 😄 

Looks good tho! Has it been UX reviewed?

2022-03-03 11:11 UTC, mictro commented on apps/cookbook/src/app/examples/page-example/advanced/page-advanced-example.component.ts
> +    <span>Custom subtitle with a long long long long name</span>
Removed

2022-03-03 11:41 UTC, mictro commented on apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
> +      <code>h1</code> tag. Usage of the page subtitle element requires the presence of a page title.
Already there for property:
: The subtitle of the page - requires the presence of a page title.

2022-03-03 11:53 UTC, mictro commented on apps/cookbook/src/app/examples/page-example/advanced/page-advanced-example.component.ts
> +    <span>Custom subtitle with a long long long long name</span>
Corrected

2022-03-03 13:25 UTC, mictro commented on libs/core/src/scss/base/_typography.scss
> +  h1,
For custom title template headings

2022-03-03 13:27 UTC, mictro commented on libs/designsystem/src/lib/components/page/page.component.scss
> +.page-header {
Because the structure has changed to be a container that contain a title and a subtitle.

2022-03-03 13:42 UTC, mictro commented on apps/cookbook/src/app/examples/page-example/advanced/page-custom-title-example.component.ts
> +      Custom subtitles with long long long long long long long long long names will wrap.
Less nitpicky solution implemented...

2022-03-04 13:17 UTC, MadsBuchmann approved these changes
Looks good to me! 
![](https://media3.giphy.com/media/3ohs7MNCq8mhWzWdyM/giphy.gif?cid=ecf05e47p2jtyfyy1ux1aozigzasm2xceqm8jf60cijirq5x&rid=giphy.gif&ct=g)

2022-03-04 13:17 UTC, merged