Enhancement/1578 remove highchart charts 2
kirbydesign/designsystem pull request #2334
Opened 2022-06-14 08:46 UTC by MadsBuchmann

## Which issue does this PR close?

This PR closes #1578

## What is the new behavior?

The highcharts dependency has been removed. All components along with specs, mocks, etc. has been removed. This means the two elements: `kirby-stock-chart-deprecated` & `kirby-chart-deprecated` can no longer be used. 

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

### Migration guide 
The new `kirby-stock` component should be used instead. It has types equivalent to the ones used in highcharts. 

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] ~~Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".~~
- [ ] ~~Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).~~

### Review  
- [X] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [X] Request that the changes are code-reviewed 
- [ ] ~~Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)~~

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2022-06-14 11:57 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/examples.routes.ts
>      path: 'stock-chart-deprecated',
Should this line be removed too?

2022-06-14 11:59 UTC, RasmusKjeldgaard requested changes
Awesome, only one minor question before we are good to go 💯

2022-06-15 06:40 UTC, MadsBuchmann commented on apps/cookbook/src/app/examples/examples.routes.ts
>      path: 'stock-chart-deprecated',
It indeed should! I've removed it.

2022-06-15 08:01 UTC, RasmusKjeldgaard approved these changes

2022-06-16 08:46 UTC, jkaltoft approved these changes

2022-06-17 08:00 UTC, merged