Fix missing backdrop on mobile
kirbydesign/designsystem pull request #2401
Opened 2022-08-02 09:25 UTC by mictro

## Which issue does this PR close?

This PR closes #2398

## What is the new behavior?

Fab sets backdrop on mobile devices.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [X] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [X] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [X] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [X] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2022-08-03 14:31 UTC, RasmusKjeldgaard commented
@mictro consider extending the _'What is the new behavior?'_ section with a description of what the problem with the existing code was, and why the `setTimeout` is no longer needed etc. Both for future us, and so I can better understand why this change does not break anything 😁

2022-08-03 14:56 UTC, RasmusKjeldgaard requested changes
It seems like the opacity transition (fade-in effect) is no longer working for the backdrop with this change.

2022-08-04 12:06 UTC, mictro commented
> Oops, timeout reintroduced and opacity animation is now visible.

2022-08-04 12:17 UTC, RasmusKjeldgaard approved these changes

2022-08-05 05:01 UTC, merged