Enhancement/2438 disable accordion item
kirbydesign/designsystem pull request #2451
Opened 2022-09-01 08:07 UTC by rasmusCCbankdata

## Which issue does this PR close?
2438

## What is the new behavior?
Possible to 'disable' an accordion-item. 

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No
- [ X] Don't know

## Are there any additional context?
See issue https://github.com/kirbydesign/designsystem/issues/2438

#####
I'm a Kirby and Angular Animations noob, so please review carefully and consider this a draft.

2022-09-02 08:14 UTC, RasmusKjeldgaard requested changes
Thank you for an awesome contribution. I have a couple of suggestions for the documentation, and there is also a tiny bit of design refinement to be done by @henrikvoetmand, that we should include when he has published the design he is working on to zeplin.

2022-09-02 08:14 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/accordion-example/accordion-example.component.html
> +<cookbook-accordion-disabled-example></cookbook-accordion-disabled-example>
I actually think we could just make e.g. Accordion Item 3 in the default example disabled instead. Dont think we need a new example for this.

2022-09-02 11:46 UTC, henrikvoetmand commented on libs/designsystem/src/lib/components/accordion/accordion-item.component.scss
> +    font-weight: utils.font-weight('light');
The text should be "semi-dark text" (#707070) and icon shluld be "semi-dark" (#8E8E8E)

2022-09-05 10:06 UTC, jkaltoft reviewed
Nice contribution. Thank you!

Depending on when this enhancement is scheduled for release we may need to rebase the branch on the Kirby v7 release branch.

2022-09-05 10:06 UTC, jkaltoft commented on libs/designsystem/src/lib/components/accordion/accordion-item.component.ts
> +  }
See other comment about Kirby v7 conflicts

2022-09-05 10:29 UTC, RasmusKjeldgaard commented on libs/designsystem/src/lib/components/accordion/accordion-item.component.html
> +    (click)="toggleExpanded()"
@jkaltoft this was the one I talked about during standup. Would probably be good to release friday as part of our ordinary release flow, as the team awaits the changes.

2022-09-05 11:14 UTC, rasmusCCbankdata commented on libs/designsystem/src/lib/components/accordion/accordion-item.component.html
> +    (click)="toggleExpanded()"
I have changed the name to _onToggleExpanded

2022-09-05 12:03 UTC, RasmusKjeldgaard approved these changes
With the new changes I think we are there. 

@jkaltoft are you OK with this as is? Then we will just have to do a bit of merging to make sure it works with v7, which I think is ok.

2022-09-05 13:24 UTC, RasmusKjeldgaard approved these changes

2022-09-05 13:26 UTC, merged