Feature/local navigation
kirbydesign/designsystem pull request #2501
Opened 2022-09-21 14:08 UTC by RasmusTraeholt

## Which issue does this PR close?

This PR closes #2186 

## What is the new behavior?

Added two new experimental features.

1. A new kirby-page directive `[kirbyPageStickyContent]` which allows custom content to be inserted between the kirby-page-title and the kirby-page-content. That will become fixed beneath the ion-header, when scrolling to its intersection point.
2. A new local-navigation component `<kirby-page-local-navigation>` that can be used in conjunction with the new kirby-page directive.

Other:
- A new `KirbyExperimentalModule` in the designsystem has been introduced in which experimental components can be declared and exposed.
- A new `ExperimentalExamplesModule` along with a new route `/examples/experimental/[path-to-experiment]` has been introduced in the cookbook app in which experimental features can be created and viewed (the new route does not have a ui link)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2022-10-11 10:50 UTC, mictro commented on libs/designsystem/src/lib/components/index.ts
> +export * from './page-local-navigation';
Always prefer explicit export, because implicit export is one of the most prominent factors for circular dependency error

2022-10-11 11:16 UTC, mictro commented on libs/designsystem/src/lib/components/page-local-navigation/index.ts
> +export * from './page-local-navigation-item';
Always prefer explicit export, because implicit export is one of the most prominent factors for circular dependency error

2022-10-11 11:41 UTC, mictro commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.ts
> +
Make it a two-way binding  
@Input  set selectedIndex(value: number)
@Output() selectedIndexChange = new EventEmitter)<number>();
Client two-way-binds with '[(selectedIndex)]=...' avoiding the (ugly) implicit requirement to listen to and update the index through itemSelect (done elsewhere but not nice).

2022-10-11 12:26 UTC, mictro commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation-item.ts
> +  id: string;
This component doesn't seem to require a unique id - remove and let the client decide it if it needs one.

2022-10-11 12:29 UTC, mictro commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation-item.ts
> +};
Loose/fluffy typing - consider something along the lines:
type BadgeIcon = {
  name: string;
  isCustom: boolean;
};
type BadgeText = {
  text: string;
};

type TabBadge = {
  content: BadgeIcon | BadgeText;
  description: string;
  color?: ThemeColor;
};

export interface NavigationTab {
  text: string;
  badge?: TabBadge;
}

2022-10-11 12:53 UTC, mictro commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.ts
> +
Decide to use _selectedIndex or selectedIndex$ not both. 
If choosing the latter you may subscribe to it in order to update the selected tab - simplifying the busy setter method.

2022-10-11 13:49 UTC, mictro commented on libs/designsystem/src/lib/components/page/page.component.ts
> +      )
takeUntil should be the last - see https://ncjamieson.com/avoiding-takeuntil-leaks/

2022-10-11 15:04 UTC, mictro requested changes
Seen from my review corner - nice work; a good test for the component is missing.

2022-10-11 15:12 UTC, RasmusTraeholt commented
Hey @mictro thank you for the great feedback. But because i just realized that position: sticky works flawlessly when used in root of ion-content (i did not work in previous iterations because i was working from drb) i have done some major refactoring, since it removes the need for intersection and mutation observers. The code should be muck simpler and cleaner now, with fewer additions.

2022-10-13 13:13 UTC, mictro commented
> 

What's there not to like :=)

2022-10-13 13:41 UTC, mictro commented
LGTM; it remains for @jkaltoft to review the styling and let @henrikvoetmand take a final look at the UX.

2022-10-13 18:25 UTC, jkaltoft requested changes
Thank you for your contribution, Rasmus.

I've reviewed mainly the stylesheets and added some comments. Most of them are suggestions for improvements - a few things need to be changed.

In general:

- Add a link from the PR to the issue it solves
- When using a solution based more or less entirely on a blog post or similar add a reference to the source(s). They can provide context and explain the solutions and the problems they solve in more detail than what fits in a comment 🙂
- Use generic and english terms in the examples (and tests) to align with the rest of the cookbook

I have not addressed accessibility issues in this review (except a single comment about using `tabindex` 🙂).

2022-10-13 18:27 UTC, jkaltoft commented
Oh, it seems that several comments have been marked as outdated due to updates being made before I got to submit the review. The comments still apply. I'll see if I can find the time to go through them again tomorrow.

2022-10-14 10:12 UTC, RasmusTraeholt commented
@jkaltoft Thank you for your feedback. I have made changes where it was needed. I don't know what to do with fluffy comments like 'it's a complicated solution for something seemingly simple'. You are welcome to make suggestions if you have a different solution in mind.

2022-10-14 10:14 UTC, RasmusTraeholt commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
> +    @media only screen and (max-width: $divider-max-width-breakpoint) {
the function does not support calculated values

2022-10-14 10:16 UTC, RasmusTraeholt commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
> +  }
It's the solution i came up with. You are welcome to make suggestions if you have a different one in mind.

2022-10-14 12:06 UTC, RasmusTraeholt commented
>     * When using a solution based more or less entirely on a blog post or similar add a reference to the source(s). They can provide context and explain the solutions and the problems they solve in more detail than what fits in a comment 🙂

What solutions are you referring too?

2022-10-14 12:54 UTC, jkaltoft commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
> +  }
My suggestion probably requires too many changes at this stage - considering it's an experimental feature - and it also challenges the design decisions. I think this is fine for now 🙂

2022-10-14 13:29 UTC, jkaltoft commented on libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
> +$divider-max-width-breakpoint: calc(#{utils.$page-content-max-width} + (#{utils.size('s')} * 2));
```suggestion
$divider-max-width-breakpoint: utils.$page-content-max-width + utils.size('s') * 2;
```

2022-10-14 13:48 UTC, jkaltoft commented
> > ```
> > * When using a solution based more or less entirely on a blog post or similar add a reference to the source(s). They can provide context and explain the solutions and the problems they solve in more detail than what fits in a comment 🙂
> > ```
> 
> What solutions are you referring too?

For example, https://css-tricks.com/bold-on-hover-without-the-layout-shift/ has a good description of the same technique that you're using to avoid layout shifts when using bold text as hover effect.

2022-10-14 14:30 UTC, jkaltoft commented
> @jkaltoft Thank you for your feedback. I have made changes where it was needed. I don't know what to do with fluffy comments like 'it's a complicated solution for something seemingly simple'. You are welcome to make suggestions if you have a different solution in mind.

Nice work, Rasmus 👍🏻

Sorry for the fluffyness. I began writing the comment before you changed the `/* HAX */` bit, but submitted it after 🙂. It still makes sense to consider, though.

I don't think you need a different solution for this. The solution is understandable - it's just more complex than using a simple border.

I'm guessing this solution was chosen because we need the border to exceed the width of `.container` on narrow viewports, but I'm not completely sure. By looking at the code itself it's not immediately obvious why it can't be done with just a 1-line `border-bottom` declaration on `.container`.

So, my suggestion is that you consider writing a short comment explaining why we need a pseudo element and several lines of code to create a border.

2022-10-14 14:32 UTC, jkaltoft submitted a review, later dismissed

2022-10-14 14:35 UTC, jkaltoft commented
I'm on vacation next week so I've approved the changes in advance 🙂

If you have any questions or comments we can follow up on it the week after next week.

2022-10-17 08:00 UTC, RasmusTraeholt commented
> I'm guessing this solution was chosen because we need the border to exceed the width of `.container` on narrow viewports, but I'm not completely sure. By looking at the code itself it's not immediately obvious why it can't be done with just a 1-line `border-bottom` declaration on `.container`.

Theres a bit more too it than just breaking constraints. The selected bottom border itself needs to have rounded corners (on all four), which is also part of the reason that it is not "just" a bottom border.

2022-10-17 08:39 UTC, RasmusTraeholt commented
> > > ```
> > > * When using a solution based more or less entirely on a blog post or similar add a reference to the source(s). They can provide context and explain the solutions and the problems they solve in more detail than what fits in a comment 🙂
> > > ```
> > 
> > 
> > What solutions are you referring too?
> 
> For example, https://css-tricks.com/bold-on-hover-without-the-layout-shift/ has a good description of the same technique that you're using to avoid layout shifts when using bold text as hover effect.

Nice find. I won't reference something i did not see or base my solution on though. But i can extend the explanation a bit :)
I believe i saw a comment on stackoverflow with a suggestion to insert a pseudo-element to avoid layout shifts. But the question it was posted to had very little in common with what i wanted to achieve. So i wont reference that either, since it could cause more confusion than relevant context.

2022-10-24 08:25 UTC, jkaltoft requested changes
Good work, Rasmus 👍🏻

The only thing left is to undo bumping the version number.

2022-10-24 08:25 UTC, jkaltoft commented on package.json
> +  "version": "7.1.2",
Bumping Kirby version should only be done when we publish, not as part of implementing a feature.

```suggestion
  "version": "7.1.1",
```

2022-10-24 08:44 UTC, henrikvoetmand commented
UX/UI review is OK!
There might be adjustments when we align with Toolbar component.

2022-10-24 08:50 UTC, jkaltoft approved these changes

2022-10-24 08:52 UTC, mictro approved these changes

2022-10-24 08:57 UTC, mictro commented
It looks good to all of us....
![download](https://user-images.githubusercontent.com/18654594/197488233-6536349e-7008-4b15-9dab-316d0b0e1e38.jpg)

2022-10-24 11:29 UTC, merged