Bugfix/list helper spec failing test
kirbydesign/designsystem pull request #2507
Opened 2022-09-28 09:54 UTC by mark-drastrup

## Which issue does this PR close?

This PR closes no issue

## What is the new behavior?

The test suites for `list-helper.ts` and `list.components.ts` are not failing anymore.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-09-28 14:13 UTC, mictro requested changes
Det er mest stilistiske kommentarer der relaterer til brug af TypeScript, konventioner og læsbarhed.

2022-09-29 10:08 UTC, mictro approved these changes

2022-09-29 11:10 UTC, jkaltoft requested changes

2022-09-29 11:10 UTC, jkaltoft commented on libs/designsystem/src/lib/components/list/list.component.scss
> +  .stand-alone-bottom-margin-#{$sizeName} {
Isn't this still unnecessary? See other comment about `getStandAloneClass()`

2022-09-29 11:10 UTC, jkaltoft commented on libs/designsystem/src/lib/components/list/list.component.ts
> +      return `stand-alone-bottom-margin-${this.standAloneSpacing}`;
```suggestion
      return this.standAloneSpacing;
```

2022-09-29 11:27 UTC, mictro approved these changes

2022-09-29 11:31 UTC, jkaltoft approved these changes

2022-09-29 11:32 UTC, merged