Refactor dropdown styles
kirbydesign/designsystem pull request #2550
Opened 2022-10-18 08:34 UTC by mark-drastrup

## Which issue does this PR close?

This PR closes #2230

## What is the new behavior?
This PR doesn't introduce new behaviour. It's purpose is to make the dropdown styles more simple and therefore easier to maintain in the future.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?
The issue refers to this [comment](https://github.com/kirbydesign/designsystem/pull/2217#discussion_r865802488), which has some suggestions on things that could be improved. There is a couple of things I wasn't able to do:

1. Removing the `is-opening` class. Without it the logic to change the horizontal or vertical direction of the modal breaks. We need to refactor the logic for the modal directions, if we want to remove this class. That is out of scope for this issue and I think that the time is better spent on other issues. 
2.  Move `kirby-calendar` specific styles to the calendar's stylesheet. The modal is used for the `year navigator` in the calender, which appears in the top right of the calendar when `Show year navigator` is checked. As far as I understand, then the issue is that from the stylesheet of the calendar, it is not possible to write styles that reaches into the child component (in this case the dropdown), without using the deprecated `::ng-deep` selector.

Notes:
The comment also asks why we are controlling opacity. If the opacity is not controlled like we do, then the user will see a noticeable flicker, when the dropdown opens and has to change direction. E.g. the user will see the dropdown open downwards and then open upwards, after it calculates that it is outside the viewport, when opening downwards.

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2022-10-24 16:00 UTC, jkaltoft requested changes
Good work.

I only have requests for minor changes.

In general it would be nice if we could move rules outside of `:host`. I think this will lower the specificity (which is good) but may be overwritten by more specific rules (which in this case is not good) 🙂. However, it may not be a feasible solution, so only change anything if it's a simple "move code from here to here" 🙂

It would also be great if the rules for `kirby-card` in different contexts/states could be moved closer together - especially the declarations that get overridden.

Unfortunately, I don't think something like this simplified example would work, but hopefully you get the idea:

```css
 kirby-card {
    display: none;
    opacity: 0;

    .is-opening & {
        display: block;
    }

    .is-open & {
        display: block;
        opacity: 1;
    }
}
```

Don't spend too much effort trying to change it 🙂

2022-10-26 07:00 UTC, mark-drastrup commented
> In general it would be nice if we could move rules outside of `:host`. I think this will lower the specificity (which is good) but may be overwritten by more specific rules (which in this case is not good) 🙂. However, it may not be a feasible solution, so only change anything if it's a simple "move code from here to here" 🙂
> 
> It would also be great if the rules for `kirby-card` in different contexts/states could be moved closer together - especially the declarations that get overridden.
> 
> Unfortunately, I don't think something like this simplified example would work, but hopefully you get the idea:
> 
> ```css
>  kirby-card {
>     display: none;
>     opacity: 0;
> 
>     .is-opening & {
>         display: block;
>     }
> 
>     .is-open & {
>         display: block;
>         opacity: 1;
>     }
> }
> ```
> 
> Don't spend too much effort trying to change it 🙂

@jkaltoft I totally agree with both points, but unfortunately it wasn't as simple "move code from here to here" for the first point 😅 And for the second point I wasn't able to find a solution to bring them closer together, than they already are. There must be a way to do it, but I wasn't able to do it in this round. I would be happy to try again or maybe work together with you on a call. I'm sure you have a better grasp on how it can be done 😄

2022-10-26 08:24 UTC, jkaltoft commented
> > In general it would be nice if we could move rules outside of `:host`. I think this will lower the specificity (which is good) but may be overwritten by more specific rules (which in this case is not good) 🙂. However, it may not be a feasible solution, so only change anything if it's a simple "move code from here to here" 🙂
> > It would also be great if the rules for `kirby-card` in different contexts/states could be moved closer together - especially the declarations that get overridden.
> > Unfortunately, I don't think something like this simplified example would work, but hopefully you get the idea:
> > ```css
> >  kirby-card {
> >     display: none;
> >     opacity: 0;
> > 
> >     .is-opening & {
> >         display: block;
> >     }
> > 
> >     .is-open & {
> >         display: block;
> >         opacity: 1;
> >     }
> > }
> > ```
> >   
> > Don't spend too much effort trying to change it 🙂
> 
> @jkaltoft I totally agree with both points, but unfortunately it wasn't as simple "move code from here to here" for the first point 😅 And for the second point I wasn't able to find a solution to bring them closer together, than they already are. There must be a way to do it, but I wasn't able to do it in this round. I would be happy to try again or maybe work together with you on a call. I'm sure you have a better grasp on how it can be done 😄

Actually, I haven't got any better ideas than the example above 🙂

2022-10-26 08:33 UTC, jkaltoft requested changes
I only have a single request for change left 🙂

2022-10-26 08:33 UTC, jkaltoft commented on libs/designsystem/src/lib/components/dropdown/dropdown.component.scss
> +  button {
Strictly speaking, this selector should be `> button `, shouldn't it? In the "before refactor" it uses a [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) ➡️ "buttons that are _direct_ children of :host"

2022-10-28 09:00 UTC, jkaltoft approved these changes, later dismissed
![giphub](https://media0.giphy.com/media/FpKKILCKqNIgIE1GZf/giphy.gif)

2022-10-28 12:48 UTC, jkaltoft approved these changes
![giphub](https://media4.giphy.com/media/eUbGqYTpWlRLO/giphy.gif)

2022-10-28 12:52 UTC, merged