Guide for secondary entries.
kirbydesign/designsystem pull request #2766
Opened 2023-01-16 13:50 UTC by kodeaben

## Which issue does this PR close?

This PR closes #2764 

## What is the new behavior?
A guild

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [-] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [-] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [-] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [-] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-01-16 20:45 UTC, RasmusKjeldgaard submitted a review, later dismissed
Solid work!

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +The `ng-package.json` file is the "hook" which tells `ng-packagr` that there is an entry wihich must be included.
```suggestion
The `ng-package.json` file is the "hook" which tells `ng-packagr` that there is an entry which must be included.
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +The file must include an empthy object `{}` and nothing else.
```suggestion
The file must include an empty object `{}` and nothing else.
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +# Move to secondary entry
One question that popped up when reading this was "How do I identify a candidate for a secondary entry"? 
E.g. how do I know if a component, service, helper etc. is something that should be moved - would be good to explain that in short here.

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +        ├── ng-packagr.json
```suggestion
        ├── ng-package.json
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +## 2. Move the sourcefolder to SE
Consider moving this step up right before step 1a. When following along the guide, I had no files to export from my public_api.ts as described in the current step 1.b.

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +git mv libs/designsystem/src/lib/component/<a-component>/* libs/designsystem/my-component/src
```suggestion
git mv libs/designsystem/src/lib/components/<a-component>/* libs/designsystem/my-component/src
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +2. The destinationfolder is the `src/` folder, not the SE root folder.
Nice gotchas 🦾

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +export * from './my.module.ts';
```suggestion
export * from './my.component';
export * from './my.module';
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +export * from './public_api.ts';
```suggestion
export * from './public_api';
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +export * from './src/index.ts';
```suggestion
export * from './src/index';
```

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +1. Remove the export from the `src/lib/*` subfolders `index.ts`.
Can we specify here that this is for instance `src/lib/components/index.ts` when moving a component?

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +# Move to secondary entry
One pointer could be that it should only have dependencies that are already secondary entries.

2023-01-16 20:45 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +Now do the same, but import `kirbyModule`.
Is this not what I just did 7.b?

2023-01-16 21:04 UTC, RasmusKjeldgaard commented on libs/designsystem/secondary-entry.md
> +## 2. Move the sourcefolder to SE
So it goes something like: 
1. Make primary entry folder with a src folder in it
2. move files
3. explain and add the rest of the files

2023-01-17 10:28 UTC, mark-drastrup requested changes
Really great write-up! I only have some minor text corrections :)

2023-01-17 10:28 UTC, mark-drastrup commented on libs/designsystem/secondary-entry.md
> +### 7.a Verify in sperate project
```suggestion
### 7.a Verify in separate project
```

2023-01-17 10:28 UTC, mark-drastrup commented on libs/designsystem/secondary-entry.md
> +    imports: [MyModule]
```suggestion
    imports: [MyComponent]
```

2023-01-17 10:28 UTC, mark-drastrup commented on libs/designsystem/secondary-entry.md
> +    imports: [MyModule]
```suggestion
    imports: [MyComponent]
```

2023-01-18 07:51 UTC, mark-drastrup approved these changes

2023-01-18 08:27 UTC, merged