[KirbyPage] Fix rare intersection observer bug
kirbydesign/designsystem pull request #2822
Opened 2023-02-02 08:57 UTC by thupi

## What is the new behavior?

There is a initializeTitle() function in Kirby-page which used to only run when the component enter or leave. However, in rare cases the reference to the title change without unmount the page component. In this case, the new title element won't be observed and there title will no be hidden and shown according to the scroll position.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Are there any additional context?

I made sure to test if running the initializeTitle() more often would cause performance issues. However, I found that assigning the same value to an existing angular propter won't cause and re-renders.

The issues could be reproduced in the flows app. However, we could reproduce it in "relationsbanken". The bug was reported in kirby-guild(https://bankdata.slack.com/archives/CGKJ1RBM4/p1674640659682029)

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] ~~Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".~~
- [ ] ~~Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).~~

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] ~~Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)~~

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-02-02 09:06 UTC, kodeaben requested changes

2023-02-02 09:06 UTC, kodeaben commented on libs/designsystem/src/lib/components/page/page.component.ts
> +    console.log('changes', changes);
Please delete this :)

2023-02-02 09:10 UTC, kodeaben approved these changes

2023-02-02 09:19 UTC, merged

2023-03-27 11:09 UTC, mictro commented
This issue was reported by Janusa Vijayathurai (@javi) but it was reported that he is no longer able to reproduce the problem.
Perhaps the new routing concept will make this a real issue - this still waits to be proven.