Adapt mock generation script to new secondary entry structure
kirbydesign/designsystem pull request #2893
Opened 2023-02-23 13:01 UTC by kodeaben

## Which issue does this PR close?

This PR closes none, hotfix

## What is the new behavior?
We now generate mocks from the root of the designsystem

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-02-27 12:03 UTC, mark-drastrup requested changes

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/alert-experimental/index.ts
> +export * from './src/public_api';
Shouldn't this be `./src/index`?

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/chart/src/shared/index.ts
> +} from './charts.types';
This file also exports a function named `isNumberArray`.

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/helpers/index.ts
> +export * from './src/public_api';
Shouldn't this be `./src/index`?

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/helpers/src/public_api.ts
> +export { ThemeColor } from '@kirbydesign/core';
Would it make sense to group all the exports from `@kirbydesign/core` in the same export?

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/list/src/directives/index.ts
> +export { InfiniteScrollDirective } from './infinite-scroll.directive';
This file also exports a const named `INFINITE_SCROLL_DEBOUNCE`

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/modal/src/public_api.ts
> +export * from './modal';
Should this be named exports for all the components inside the folder? The folder contains:

- action-sheet
- alert
- footer
- services

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/modal/src/public_api.ts
> +export * from './modal-wrapper';
Same as above? Should it be a named export for the modal-wrapper component?

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/testing-base/src/lib/components/mock.modal.component.ts
> +import { OverlayEventDetail } from '@kirbydesign/designsystem/modal';
This one should really be `import { OverlayEventDetail } from '@ionic/core/components';`

2023-02-27 12:03 UTC, mark-drastrup commented on libs/designsystem/testing-base/src/tsconfig.json
>    "compilerOptions": {
Can we remove the empty `compilerOptions`, or will that cause an error?

2023-02-28 09:10 UTC, kodeaben commented on libs/designsystem/alert-experimental/index.ts
> +export * from './src/public_api';
the complier complained again, and I dunno why..

2023-02-28 09:15 UTC, kodeaben commented on libs/designsystem/modal/src/public_api.ts
> +export * from './modal';
no, because the `index` in `./modal` has the named exports

2023-03-02 08:02 UTC, kodeaben commented on libs/designsystem/helpers/src/public_api.ts
> +export { ThemeColor } from '@kirbydesign/core';
Good eye :D

2023-03-02 08:02 UTC, kodeaben commented on libs/designsystem/helpers/index.ts
> +export * from './src/public_api';
noo ;)

2023-03-02 08:03 UTC, kodeaben commented on libs/designsystem/modal/src/public_api.ts
> +export * from './modal-wrapper';
same

2023-08-22 08:19 UTC, jakobe commented
We should take into account NX's new ability to publish packages without manually defining and maintaining secondary entry points: https://twitter.com/juristr/status/1692537684659785802?t=-02nwI1Shj2nCmgnj9Oj4Q&s=31

2023-11-09 12:20 UTC, RasmusKjeldgaard commented
We should altso add a host attribute, e.g. 'mock' for any generated mocks to avoid this problem: https://github.com/kirbydesign/designsystem/issues/3225

2024-01-24 12:10 UTC, closed without merging

2024-01-24 12:11 UTC, alxzak commented
will not develop this... yet..