Add extra small checkboxes
kirbydesign/designsystem pull request #3141
Opened 2023-06-30 08:50 UTC by AgreSanGit

## Which issue does this PR close?

This PR closes #2991 

## What is the new behavior?

Extra small checkbox now gives a smaller checkbox.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-07-04 11:46 UTC, mark-drastrup requested changes
Looks really good! My only comment is to update the cookbook text, that says "The checkbox and checkmark always have the same size.", and to update the vertical placement of the "xs: 32px" in the example :)

2023-08-04 08:34 UTC, RasmusKjeldgaard requested changes

2023-08-04 08:34 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +      align-items: center;
I think this is the right choice, but note that the multiline checkbox looks different now:
Before: 
<img width="500" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/a266ef76-3e01-4dea-a880-2b0b7b02a298">

After: 
<img width="494" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/14141f90-75ca-4575-be2e-362fd29d6321">

2023-08-04 08:34 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
> +    and checkmark have the same size unless you choose XS.
Consider wording here, so the difference is a bit easier to understand. How about something like:  

> The small and medium sizes apply to the clickable/tapable area (highlighted in the examples below) while the checkbox itself remains the same size. 
> 
> The extra small size applies to both click-area and checkbox, but should be used with caution. 
> 
> The extra small size is mainly intended for use in expert systems or information dense interfaces where the reduced size is a necessity but note that it comes at the cost of degraded accessibility.

2023-08-04 08:35 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +      align-items: center;
Verify with UX and I also think we should aim to get this into v9 so we can add a small note about this alignment to the migration notes. Teams might have compensated for this themselves and aligned the checkbox horizontally.

2023-08-31 10:34 UTC, AgreSanGit commented on apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
> +    and checkmark have the same size unless you choose XS.
Check

2023-09-08 07:04 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +      align-items: center;
Scratch that, after discussing with our UI designers it is clear that this should be reverted so the checkbox is top-aligned :D

2024-02-05 21:58 UTC, RasmusKjeldgaard requested changes

2024-02-05 21:58 UTC, RasmusKjeldgaard commented on libs/designsystem/calendar/src/calendar.component.scss
> +
```suggestion
```

2024-02-05 21:58 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +        --border-radius: 4px;
Consider using utils.sizes here

2024-02-05 21:58 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +    }
Consider removing this block - I do not think it has any effect on the layout?

2024-02-05 21:58 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
>    <cookbook-checkbox-sizes-example #checkboxSizesExample></cookbook-checkbox-sizes-example>
Consider adding a divider inside the `cookbook-checkbox-sizes-example` so it looks something like this:

```
<kirby-checkbox size="xs" text="Extra Small"></kirby-checkbox>
<kirby-divider [hasMargin]="true"></kirby-divider>
<kirby-checkbox size="sm" text="Small"></kirby-checkbox>
<kirby-checkbox size="md" text="Medium (default)"></kirby-checkbox>
```

<img width="645" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/4d1d6aa4-a52e-48cc-a175-c037c1d9781d">

2024-02-05 21:58 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
>            padding-bottom: $vertical-padding;
Consider some light boyscouting 😇 
```suggestion
          padding-block: $vertical-padding;
```

2024-02-05 21:58 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +    :host-context(.checkbox-xs),
This should not be necessary, as far as I remember it was an old cookbook thing that leaked into our implementation
```suggestion
```

2024-02-06 06:22 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +      :host-context(.checkbox-#{$size}),
This should not be necessary, as far as I remember it was an old cookbook thing that leaked into our implementation

```suggestion
```

2024-02-07 08:59 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.scss
> +        font-size: #{utils.font-size('s')};
```suggestion
        font-size: utils.font-size('s');
```

2024-02-07 13:35 UTC, RasmusKjeldgaard approved these changes

2024-02-07 13:35 UTC, merged