Bugfix: kirby checkbox does now trigger changes within reactive forms
kirbydesign/designsystem pull request #3158
Opened 2023-07-06 12:23 UTC by AgreSanGit

## Which issue does this PR close?

This PR closes #2804 

## What is the new behavior?

ControlValueAccessor implemented so kirby checkbox does now trigger changes within reactive forms

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-07-11 09:10 UTC, mark-drastrup requested changes, later dismissed
Great work @AgreSanGit :D I have have some nitty gritty comments! :)

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  private onTouched: () => void = () => {};
```suggestion
  private _onTouched = () => {};
```

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  private onChange: (value: boolean) => void = () => {};
```suggestion
  private _onChange: (value: boolean) => void = () => {};
```

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  private onChange: (value: boolean) => void = () => {};
This is just to follow the naming convention in other components, that also implements the ControlValueAccessor interface :)

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  private onTouched: () => void = () => {};
This is just to follow the naming convention in other components, that also implements the ControlValueAccessor interface :)

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +  describe('ControlValueAccessor implementation', () => {
```suggestion
  describe('implementing ControlValueAccessor interface', () => {
```

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +  describe('ControlValueAccessor implementation', () => {
This is not important, but it's just the description that is being used in other test files, that tests for ControlCalueAccessor implementation :)

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +      expect(onChangeSpy).toHaveBeenCalledWith(newValue);
```suggestion
      expect(onChangeSpy).toHaveBeenCalledOnceWith(newValue);
```

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +      expect(onChangeSpy).toHaveBeenCalledWith(newValue);
This is just to make sure that the onChange function is only called once :)

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +      expect(onTouchedSpy).toHaveBeenCalled();
```suggestion
      expect(onTouchedSpy).toHaveBeenCalled(); 
      expect(onTouchedSpy).toHaveBeenCalledTimes(1);
```

2023-07-11 09:10 UTC, mark-drastrup commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +      expect(onTouchedSpy).toHaveBeenCalled();
Again just to make sure that the onTouched function is only called once :)

2023-09-04 13:34 UTC, RasmusKjeldgaard requested changes
Good job on implementation and test!

Apart from a couple of minor suggestions, I think the only thing missing is a good example of this in a reactive form, like we have for radio-groups: https://cookbook.kirby.design/#/home/showcase/radio

2023-09-04 13:34 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.spec.ts
> +      expect(onTouchedSpy).toHaveBeenCalled();
```suggestion
```

I suggest to remove this line to avoid redundant expects, as it is covered by `toHaveBeenCalledTimes(1)` on the next line

2023-09-04 13:34 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  //ControleValueAcessor
```suggestion
  // Initialize empty ControlValueAccessor callback functions
```
Consider giving a bit of context in this comment

2023-09-04 13:34 UTC, RasmusKjeldgaard commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  }
Consider just copying this whole block directly from `dropdown.component.ts` (except for the implementation of writeValue of course) for consistency of comments and so on.

2023-09-04 14:08 UTC, RasmusKjeldgaard commented
I think we should label this as a feature instead of a fix. I know the original issue is a bug report, but we are adding a new feature cleanly here, not fixing existing functionality.

2023-09-19 05:46 UTC, jakobe requested changes
Hi @AgreSanGit ,

1 important comment and a few copy-pastes to fix ;)

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
Please consider readability: order and grouping of imports: 
```suggestion
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

import { UniqueIdGenerator } from '@kirbydesign/designsystem/helpers';
```

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  // Initialize empty ControlValueAccessor callback functions
Consider wording:
```suggestion
  // Initialize default ControlValueAccessor callback functions (noop)
```

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +   * Sets the select's value. Part of the ControlValueAccessor interface
Copy pasted from somehere? ;)
```suggestion
   * Sets the checkbox's value. Part of the ControlValueAccessor interface
```

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +   * Saves a callback function to be invoked when the select's value
Copy pasted from somehere? ;)
```suggestion
   * Saves a callback function to be invoked when the checkbox's value
```

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +   * Saves a callback function to be invoked when the select is blurred
Copy pasted from somehere? ;)
```suggestion
   * Saves a callback function to be invoked when the checkbox is blurred
```

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +   * Disables the select. Part of the ControlValueAccessor interface required
Copy pasted from somehere? ;)
```suggestion
   * Disables the checkbox. Part of the ControlValueAccessor interface required
```

2023-09-19 05:46 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +    this._onTouched();
This should be called on blur, not when checked state changes.

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
> +  <h3>Reactive Forms</h3>
```suggestion
  <h2>Angular Forms</h2>
```

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
> +  <h3>Reactive Forms</h3>
I still think we can make this a bit easier to digest, possibly by adding back a little bit of the text inspired by the radio group example right below the Angular Forms heading:

> The checkbox can be used directly in [template driven](https://angular.io/guide/forms) and [reactive forms](https://angular.io/guide/reactive-forms).
> To use checkbox in a reactive form, bind your form control to <kirby-checkbox> with simple data binding:

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts
> +  </kirby-checkbox>
Consider adding a couple of checkboxes more, and reuse text from Radio Examples: 

<img width="180" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/312fd969-79d2-442f-82f8-67d233e4ef4a">

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/checkbox-example/checkbox-example.module.ts
> +import { CheckboxReativeFormsExampleComponent } from './examples/reactive-forms';
```suggestion
import { CheckboxReactiveFormsExampleComponent } from './examples/reactive-forms';

```

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts
> +<fieldset>
Consider using `cookbook-example-configuration-wrapper` here.

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts
> +    `,
```suggestion
toggleCanSelectFavorite() {
  this.canSelectFavorite = !this.canSelectFavorite;

  if (this.canSelectFavorite) {
    this.form.get('isChecked')?.enable();
  } else {
    this.form.get('isChecked')?.disable();
  }
}
`,
```

2023-09-19 06:20 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts
> +  favoriteRequired = true;
Consider removing `favoriteRequired` if it is not used in the example

2023-10-02 11:11 UTC, RasmusKjeldgaard approved these changes

2023-10-02 13:34 UTC, RasmusKjeldgaard requested changes

2023-10-02 13:34 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts
> +  formValue: any;
I think we should clean this example up, so it is easier to understand.
Let us talk about this thursday!

2023-11-21 12:44 UTC, RasmusKjeldgaard approved these changes

2023-11-22 07:22 UTC, jakobe approved these changes

2023-11-22 07:22 UTC, merged