Optimize content scroll listening in modal
kirbydesign/designsystem pull request #3163
Opened 2023-07-10 12:02 UTC by AgreSanGit

## Which issue does this PR close?

This PR closes #3044

## What is the new behavior?

Optimize content scroll listening in modal. Now listening to the current breakpoint and enabling/disabling the subscription accordingly for ionScroll. On desktop disable IonScroll listening.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-07-31 12:36 UTC, RasmusKjeldgaard submitted a review, later dismissed

2023-07-31 12:36 UTC, RasmusKjeldgaard commented on libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.spec.ts
> +describe('initializeContentScrollListening', () => {
Consider adding this describe block to the top level describe block to avoid duplicate setup

2023-07-31 12:36 UTC, RasmusKjeldgaard commented on libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
> +    if (this.platform.isPhabletOrBigger()) return;
Would be great to find a way to do this dynamically if the screen resizes, to satisfy the request in the issue: 

> Ideally we want to listen to the current breakpoint and enable/disable the subscription accordingly.

2023-12-13 13:05 UTC, jakobe requested changes

2023-12-13 13:05 UTC, jakobe commented on libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.spec.ts
> +      await new Promise((resolve) => setTimeout(resolve, 500));
Please replace with more performant state detection:
```suggestion
      await TestHelper.whenTrue(() => spectator.component.isContentScrolled);
```

2023-12-18 13:08 UTC, jakobe approved these changes

2023-12-18 13:13 UTC, merged