Bug/3217 allow nested flag component in header
kirbydesign/designsystem pull request #3220
Opened 2023-08-31 12:28 UTC by NillerW

## Which issue does this PR close?

This PR closes #3217

## What is the new behavior?

By using ngProjectAs attribute on the a wrapper component, allows component nesting of avatar, kirby-progress-circle and flag in Kirby-header component.

The core functionality is still the same.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

No tests has been added as existing tests covers the same functionality.

No cookbook examples has been added, since it should not be encouraged to make this bypass unless you know what you're doing - in agreement with @jakobe.

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed] (Not relevant)

2023-08-31 12:29 UTC, NillerW commented on libs/designsystem/header/src/header.component.ts
> +    this.avatarReadyToRenderAfterContentProjection = true;
Necessary due to the way kirby-progress-circle determines it's placement on the screen in relation to content projected content.

2023-11-01 08:14 UTC, NillerW commented on libs/designsystem/header/src/header.component.ts
> +    this.avatarReadyToRenderAfterContentProjection = true;
Can no longer reproduce

2024-01-17 07:44 UTC, jakobe requested changes
Looks good 👌🏻 

Only one thing to consider regarding life cycle change from `ngAfterContentInit` to  `ngAfterContentChecked`, see comment on specific lines.

Please also add a/some test(s) for the changes 🤞🏻 

Rest of comments is mainly around aligning code with rest of codebase 😇

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/calendar/src/calendar.component.scss
> +
Please revert unrelated change 🙏🏻  (it's a Prettier thing, but this file is not related to the issue at hand)
```suggestion
```

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/header/src/header.component.ts
> +  public onTitleClick(event: PointerEvent) {
Please revert to align with rest of codebase:
```suggestion
  onTitleClick(event: PointerEvent) {
```

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/header/src/header.component.ts
> +  public _actionGroupInjector: Injector;
Please revert to align with rest of codebase:
```suggestion
 _actionGroupInjector: Injector;
```

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/header/src/header.component.ts
> +  public ngOnInit(): void {
Please revert to align with rest of codebase:
```suggestion
  ngOnInit(): void {
```

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/header/src/header.component.ts
> +  public ngAfterContentChecked(): void {
Please align with rest of codebase:
```suggestion
  ngAfterContentChecked(): void {
```

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/header/src/header.component.ts
> +    const avatarPresent: boolean = this.avatarContainerElement?.nativeElement.children.length > 0;
Consider checking for visibility instead to better reflect the UI logic for the avatar container:
```suggestion
    const avatarPresent: boolean = this.avatarContainerElement?.nativeElement. checkVisibility();
```

2024-01-17 07:44 UTC, jakobe commented on libs/designsystem/header/src/header.component.ts
> +  public ngAfterContentChecked(): void {
Are we sure we want to change this from `ngAfterContentInit` to `ngAfterContentChecked `? 🤔 Is it needed for anything specific?

2024-09-26 15:02 UTC, RasmusKjeldgaard commented
Closing this, as we can look into this functionality when converting to web-components instead.
Please reopen if needed.

2024-09-26 15:02 UTC, closed without merging