Header: add support for subtitle1 and subtitle2 as string arrays
kirbydesign/designsystem pull request #3231
Opened 2023-09-13 07:36 UTC by jakobe

## Which issue does this PR close?

This PR closes #3221

## What is the new behavior?

As stated in the issue: #3221 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-09-22 08:01 UTC, RasmusKjeldgaard requested changes
Stellar work ❤️ Got nothing on the implementation and test - all very neat!
Only a couple of small details on the docs to avoid confusion.

2023-09-22 08:01 UTC, RasmusKjeldgaard commented on libs/designsystem/calendar/src/calendar.component.scss
> +
Consider reverting unrelated change.

2023-09-22 08:01 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/header-example/examples/subtitles.ts
> +  template: `<kirby-header [title]="'Title'" [subtitle1]="['Mrs. Lady Like Tiff Tuff Escargoon Tokkori ', '&', 'Mr. Chef Kawasaki Tokkori']">
```suggestion
  template: `<kirby-header [title]="'Title'" [subtitle1]="['Mrs. Lady Like Tiff Tuff Escargoon Tokkori', '&', 'Mr. Chef Kawasaki Tokkori']">
```

Consider removing this space to avoid confusion - consumers might think they need to supply a space

2023-09-22 08:01 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/header-example/examples/subtitles.ts
> +  template: `<kirby-header [title]="'Title'" [subtitle1]="['Mrs. Lady Like Tiff Tuff Escargoon Tokkori ', '&', 'Mr. Chef Kawasaki Tokkori']">
Consider either longer names or reducing the example viewer width, so it showcases better when the page reaches its max width:
<img width="1046" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/03bbc552-d802-40e0-8cd7-a590038dac14">

2023-09-22 08:05 UTC, jakobe commented on libs/designsystem/calendar/src/calendar.component.scss
> +
Comes from develop...

2023-09-22 08:12 UTC, RasmusKjeldgaard commented on libs/designsystem/calendar/src/calendar.component.scss
> +
```suggestion
```

2023-09-25 06:48 UTC, RasmusKjeldgaard approved these changes
Awesome!!

2023-09-25 06:48 UTC, merged