Upgrade to Ionic 7
kirbydesign/designsystem pull request #3232
Opened 2023-09-13 08:23 UTC by RasmusKjeldgaard

## Which issue does this PR close?

This PR closes # (insert issue number here)

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-09-20 11:42 UTC, RasmusKjeldgaard commented on libs/designsystem/modal/src/modal/services/modal-animation-builder.service.ts
> +    return (baseEl: HTMLElement, opts: any): Animation => {
This looks funky, but between v6.7.5 and v7.3.3, the core package exports was changed from default exports to named exports, and now `ModalAnimationOptions` is only available internally to Ionic. 

v6.7.5:
`export * from './components/modal/modal-interface';`

v7.3.3:
`export { ModalOptions, ModalCustomEvent } from './components/modal/modal-interface';`

2023-09-20 11:44 UTC, RasmusKjeldgaard commented on libs/designsystem/modal/src/modal/services/modal-animation-builder.service.ts
> +    return (baseEl: HTMLElement, opts: any): Animation => {
So, should we copy out the type from Ionic core, or continue with `any`?

2023-10-05 16:02 UTC, jakobe requested changes
A few small things—otherwise great work! 💪🏻 👌🏻 👏🏻

2023-10-05 16:02 UTC, jakobe commented on libs/designsystem/checkbox/src/checkbox.component.ts
> +  size?: 'xs' | 'sm' | 'md' = 'md';
Nitty gritty, but I guess this is no longer optional (i.e. can be `undefined`) if it has a default value? 🤔 
```suggestion
  size: 'xs' | 'sm' | 'md' = 'md';
```

2023-10-05 16:02 UTC, jakobe commented on libs/designsystem/helpers/src/ionic-element-part-service.ts
> +export class IonicElementPartService {
Consider naming - all other helpers in this folder ends with `-helper`...

2023-10-05 16:02 UTC, jakobe commented on libs/designsystem/modal/src/modal/services/modal-animation-builder.service.ts
> +    return (baseEl: HTMLElement, opts: any): Animation => {
@RasmusKjeldgaard maybe just inline a type with the property from `ModalAnimationOptions` that we need?
```suggestion
    return (baseEl: HTMLElement, opts: { presentingEl?: HTMLElement }): Animation => {
```

2023-10-05 16:02 UTC, jakobe commented on libs/designsystem/modal/src/modal/services/modal-animation-builder.service.ts
> +    return (baseEl: HTMLElement, opts: any, duration = this.duration): Animation => {
```suggestion
    return (baseEl: HTMLElement, opts: { presentingEl?: HTMLElement }, duration = this.duration): Animation => {
```

2023-10-05 16:02 UTC, jakobe commented on libs/designsystem/page/src/page.component.ts
> +    );
Nice! 👌🏻

2023-10-05 16:02 UTC, jakobe commented on libs/designsystem/radio/src/radio.component.ts
> +  size?: 'xs' | 'sm' | 'md' = 'md';
Nitty gritty, but I guess this is no longer optional (i.e. can be `undefined`) if it has a default value? 🤔 
```suggestion
  size: 'xs' | 'sm' | 'md' = 'md';
```

2023-10-06 13:22 UTC, RasmusKjeldgaard commented on libs/designsystem/modal/src/modal/services/modal-animation-builder.service.ts
> +    return (baseEl: HTMLElement, opts: any): Animation => {
Excellent, good idea!

2023-10-09 13:18 UTC, RasmusKjeldgaard commented on libs/designsystem/helpers/src/ionic-element-part-service.ts
> +export class IonicElementPartService {
Renamed to `IonicElementPartHelper` in 7b2134cc6805ff04c46a02cc0cc75193ba61b052

2023-10-09 15:13 UTC, jakobe approved these changes

2023-10-10 06:41 UTC, merged