feat: add decoration colors
kirbydesign/designsystem pull request #3288
Opened 2023-11-20 16:57 UTC by jakobe

## Which issue does this PR close?

This PR closes #3140

## What is the new behavior?

New decoration colors added, especially for use in charts.
Notification colors, toast and flag updated accordingly.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2023-11-21 14:00 UTC, RasmusKjeldgaard requested changes
Nice use of description list, I learned something today!

This is a first round of docs comments for consideration, will look at the implementation and test ASAP.

2023-11-21 14:00 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/toast-example/toast-example.component.html
> +<button kirby-button (click)="showToast('warning')">Show toast (warning)</button>
```suggestion
<button kirby-button (click)="showToast()">Show default toast (success)</button>
<button kirby-button (click)="showToast('warning')">Show toast (warning)</button>
```

2023-11-21 14:00 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/examples/toast-example/toast-example.component.html
> +<button kirby-button (click)="showToast('warning')">Show toast (warning)</button>
Consider simplifying this example so readers will not misinterpret it as a difference between success and default.

2023-11-21 14:00 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.html
> +      <h2 class="color-name">{{ color.name }}</h2>
```suggestion
      <h3 class="color-name">{{ color.name }}</h3>
```
Probably irrelevant given the current state of our docs but I think this should be a h3

2023-11-21 14:00 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.scss
> +
consider adding gap to the grid here to act as a minimum spacing between color samples
<img width="406" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/8f3b4845-77da-4a03-a6ac-846ae40cde0b">
vs
<img width="437" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/9227f707-4688-485b-9d62-f3ed6c486667">

2023-11-21 14:00 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.html
> +
Should we add a couple of lines about usage to this file? I know it is missing for everything else, so might not be necessary. 

But if we are adding this with the assumption that people are going to be checking it out on the cookbook page, now could be the right time.

2023-11-21 14:00 UTC, RasmusKjeldgaard commented on libs/core/src/scss/themes/_colors.scss
>    'danger': #ee0d0d,
The original issue mentions extending the text-colors too, with:
```
positive: green-80
negative: red-70 
```

I realize it is a wee bit out of scope, but would be nice to avoid another issue/PR roundtrip :D

2023-11-23 11:41 UTC, jakobe commented on apps/cookbook/src/app/examples/toast-example/toast-example.component.html
> +<button kirby-button (click)="showToast('warning')">Show toast (warning)</button>
Nice point 👌🏻 
Done 👍🏻

2023-11-23 12:19 UTC, jakobe commented on apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.html
> +
🙈 :shipit:

2023-11-23 13:18 UTC, RasmusKjeldgaard requested changes
Everything looks good except for a small detail in the docs!

2023-11-23 13:18 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.scss
> +  .color-sample.#{$color-name} {
The "color-sample-example" section should have the `color-sample` class added to preserve the functionality of the section "_Example use (Click on a color below to change it)_"

2023-11-23 13:18 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.scss
> +  .color-sample.#{$color-name} {
Right now it is just blank in stead of this:
<img width="163" alt="image" src="https://github.com/kirbydesign/designsystem/assets/42470636/dc174f7e-0129-4d3c-b16f-4ce6162709df">

2023-11-23 15:12 UTC, RasmusKjeldgaard approved these changes
👏

2023-11-23 15:12 UTC, merged