Fix broken links in issue templates
kirbydesign/designsystem pull request #3347
Opened 2024-01-19 15:21 UTC by GizemSavci

## Which issue does this PR close?

This PR closes # 3339

## What is the new behavior?

Fix broken links in issue templates.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2024-02-01 11:07 UTC, RasmusKjeldgaard requested changes
Thank you so much for this contribution @GizemSavci!
I've added a couple of suggestions that you should be able to commit directly if you want. Otherwise this seems ready to merge 😊

2024-02-01 11:07 UTC, RasmusKjeldgaard commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/d4cf30c680e0eca4fed82205ffe4343996663380/.github/SUPPORT.md#team
This currently points to a specific commit instead of the develop branch itself, so new changes to the file will not be reflected on the link 😊  
```suggestion
- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done
```

2024-02-01 11:07 UTC, RasmusKjeldgaard commented on package-lock.json
> +        "eslint-plugin-import": "latest",
Consider reverting this unrelated change.
```suggestion
        "eslint-plugin-import": "*",
```

2024-02-05 14:21 UTC, GizemSavci commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/d4cf30c680e0eca4fed82205ffe4343996663380/.github/SUPPORT.md#team
Thank you @RasmusKjeldgaard 🥰 I changed the link.

2024-02-05 14:22 UTC, GizemSavci commented on package-lock.json
> +        "eslint-plugin-import": "latest",
Thank you, I reverted.😊

2024-02-05 20:55 UTC, RasmusKjeldgaard approved these changes
🎉

2024-02-05 20:57 UTC, GizemSavci commented
🩷

2024-02-05 20:59 UTC, merged