Enhancement/3363 enhancement visual regression tests in chromatic
kirbydesign/designsystem pull request #3403
Opened 2024-03-04 13:41 UTC by jkaltoft

## Which issue does this PR close?

This PR closes # (insert issue number here)

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2024-03-14 07:15 UTC, RasmusKjeldgaard requested changes

2024-03-14 07:15 UTC, RasmusKjeldgaard commented on .github/workflows/chromatic.yml
> +        types: [ labeled ]
If we add the synchronize label here, we can run the chromatic action whenever a new commit is added, and the label is present. That might be a better default?
```suggestion
        types: [labeled, synchronize]
```

2024-03-14 07:15 UTC, RasmusKjeldgaard commented on .github/workflows/chromatic.yml
> +name: "Chromatic"
Consider a more descriptive name 
```suggestion
name: "Visual Regression Tests - Chromatic"
```

2024-03-14 07:15 UTC, RasmusKjeldgaard commented on .github/workflows/chromatic.yml
> +    if: ${{ github.event.label.name == 'chromatic' }}
If we add the synchronize pull request type, we also need to check for the label name on the pull-request itself.

```suggestion
    if: ${{ github.event.label.name == 'chromatic' || contains(github.event.pull_request.labels.*.name, 'chromatic') }}
```

2024-03-14 10:26 UTC, jkaltoft commented on .github/workflows/chromatic.yml
> +        types: [ labeled ]
This (and the condition check on the job below) is exactly what I was looking for. Thanks.

2024-03-14 10:27 UTC, jkaltoft reviewed
The suggested changes are exactly what I was looking for. Thanks.

2024-03-14 10:29 UTC, jkaltoft commented on .github/workflows/chromatic.yml
> +name: "Chromatic"
I agree that this should be a descriptive name. I just went with the simplest name to get started 🙂

2024-03-18 06:37 UTC, RasmusKjeldgaard approved these changes, later dismissed

2024-03-18 14:02 UTC, RasmusKjeldgaard approved these changes, later dismissed

2024-03-18 15:01 UTC, RasmusKjeldgaard approved these changes
🎉

2024-03-18 15:01 UTC, merged