Customizable icon asset path
kirbydesign/designsystem pull request #3601
Opened 2024-09-12 08:58 UTC by andershessellund

This adds the possibility of customizing the asset path used to fetch icons. The default remains unchanged `assets/kirby/icons/svg` .

The path is customized by providing an injection token `BUILT_IN_ICONS_URL_TOKEN` with the path to the icons.

2024-09-13 09:11 UTC, Fuzzy3 requested changes
Really nice PR ! Just a few changes needed in the code, and then its good to go. 
Besides this it would also be nice if you could update the Icon page in the cookbook and also the README on how to override this icon-path. 
For inspiration we just made a short "setup" section for the DataTable component, maybe this could be written somewhat similarly. [https://cookbook.kirby.design/branch/kby-develop/#/home/showcase/data-table](https://cookbook.kirby.design/branch/kby-develop/#/home/showcase/data-table)

2024-09-13 09:11 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +    const baseUrl = this.builtInIconsUrl ?? DEFAULT_BUILT_IN_ICONS_URL;
Instead of this, you can provide a "factory"-method as an option to the injection token, which will return a default value if not overridden. Check this stackblitz as an example: https://stackblitz.com/edit/angular-default-value-token?file=src%2Fapp%2Fapp.component.ts

2024-09-13 09:11 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +    const baseUrl = this.builtInIconsUrl ?? DEFAULT_BUILT_IN_ICONS_URL;
Then you can also get rid of the "optional: true" in the inject itself

2024-09-13 09:11 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +    for (const { name, svg } of kirbyIconSettings.icons) {
```suggestion
    kirbyIconSettings.icons.forEach((icon) => {
```

2024-09-13 09:11 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +export const DEFAULT_BUILT_IN_ICONS_URL = 'assets/kirby/icons/svg';
```suggestion
export const DEFAULT_BUILT_IN_ICONS_URL = 'assets/kirby/icons/svg/';
```

2024-09-13 09:11 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +  private builtInIconsUrl = inject(BUILT_IN_ICONS_URL, { optional: true });
Move this to the constructor, then its similar to what we do other places in Kirby 😄  I know it doesn't change anything, but its just nice to have to the same way.

2024-09-13 09:13 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +      const url = baseUrlWithSlash + svg;
```suggestion
      const url = baseUrlWithSlash + icon.svg;
```

2024-09-13 09:13 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +      this.addIcon(name, url);
```suggestion
      this.addIcon(icon.name, url);
```

2024-09-13 09:13 UTC, Fuzzy3 commented on libs/designsystem/icon/src/icon-registry.service.ts
> +    }
```suggestion
    });
```

2024-09-13 09:36 UTC, andershessellund commented on libs/designsystem/icon/src/icon-registry.service.ts
> +  private builtInIconsUrl = inject(BUILT_IN_ICONS_URL, { optional: true });
IMO constructor injection is the legacy way to do it, but it is entirely up to you.

2024-09-19 10:34 UTC, jakobe commented on apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.html
> +
Consider adding that the `BUILT_IN_ICONS_URL` token can be set both to a relative and an absolute path.

2024-09-19 10:34 UTC, jakobe commented on apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.html
> +
Consider adding an inline code snippet that shows how to add the token to app providers

2024-09-19 12:50 UTC, jakobe approved these changes
👌🏻

2024-09-19 18:51 UTC, Fuzzy3 approved these changes

2024-09-19 18:52 UTC, merged