Add translation service and initial translations
kirbydesign/designsystem pull request #3717
Opened 2024-11-21 10:27 UTC by RasmusKjeldgaard

## Which issue does this PR close?

This PR closes # (insert issue number here)

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2024-11-21 21:25 UTC, Fuzzy3 requested changes
Really good reflections in your draft notes ! I don't think there would be a more clean way of handling translations than this, for such a small set of translations. let's not bring out the big hammer and do reactiveness before it is actually an identified need. good PR, great scope ! ❤️

2024-11-21 21:25 UTC, Fuzzy3 commented on libs/designsystem/shared/src/translation/translation.service.ts
> +  setCurrentTranslation(localeId: string): string {
```suggestion
  setTranslation(localeId: string): string {
```

2024-11-21 21:25 UTC, Fuzzy3 commented on libs/designsystem/shared/src/translation/translation.service.ts
> +    const baseLocaleId = localeId.split('-')[0];
Don't know if destructuring is more readable 🤔 
```suggestion
    const [baseLocaleId] = localeId.split('-');
```

2024-11-21 21:25 UTC, Fuzzy3 commented on libs/designsystem/shared/src/translation/translation.service.ts
> +  public currentTranslation: Translation = en;
Could also be "activeTranslation"
```suggestion
  public activeTranslation: Translation = en;
```

2024-11-21 21:25 UTC, Fuzzy3 commented on libs/designsystem/shared/src/translation/translation.service.ts
> +      console.warn(`Translation not found for locale "${this.localeId}", falling back to "en"`);
Well... I guess there could be a scenario where the currentTranslation was changed to danish earlier - and then I guess we are not falling back to english. I don't think that is a likely scenario though 😆

2024-11-22 08:12 UTC, jakobe reviewed
Great work, Raz 👌🏻 

I like the scoping you've done, we can always later add support for changes to the locale 👍🏻 

Maybe we can shorten the syntax a bit? I.e.
Consuming component:
```ts
constructor(
    ...,
    public translations: TranslationService
  ) {
```
Template binding:
`[attr.aria-label]="translations.get('previousMonth')"`

and then in `TranslationService:`
```ts
get(key: keyof Translation): string {
  return this.currentTranslation[key];
}
```

2024-11-22 09:48 UTC, RasmusKjeldgaard commented on libs/designsystem/shared/src/translation/translation.service.ts
> +    const baseLocaleId = localeId.split('-')[0];
In this case I think it reads a bit better that you can go "split string and take the first substring" rather than having to understand the destructuring part 🤔 So I'll leave it as is if ok.

2024-11-22 09:49 UTC, RasmusKjeldgaard commented on libs/designsystem/shared/src/translation/translation.service.ts
> +      console.warn(`Translation not found for locale "${this.localeId}", falling back to "en"`);
Good point, I'll make it so it takes the fallback value from the activeTranslation instead 😘

2024-12-03 15:49 UTC, RasmusKjeldgaard commented on libs/designsystem/calendar/src/calendar.component.ts
> +    public translations: TranslationService
Should we make getters in each component to avoid making the service public here?

2024-12-04 09:58 UTC, jakobe reviewed
Really nice work 👌🏻 
Great docs!

2024-12-04 09:58 UTC, jakobe commented on apps/cookbook/src/app/localization/localization.component.html
> +        <cookbook-da-locale-provider style="position: relative">
Maybe move inline style to scss?

2024-12-04 09:58 UTC, jakobe commented on apps/cookbook/src/app/localization/localization.component.html
> +        <cookbook-en-locale-provider style="position: relative">
Maybe move inline style to scss?

2024-12-04 09:58 UTC, jakobe commented on apps/cookbook/src/app/localization/localization.component.html
> +    If custom components are closely coupled to Kirby and need to use identical translations,
Maybe improve readability:
```suggestion
    When developing custom components closely coupled to Kirby that need to use identical translations,
```

2024-12-04 09:58 UTC, jakobe commented on apps/cookbook/src/app/localization/localization.component.html
> +    This can be done by injecting the service and getting any key defined in the
Maybe improve readability:
```suggestion
    This can be done by injecting the service into the component and get any key defined in the
```

2024-12-04 09:58 UTC, jakobe commented on apps/cookbook/src/app/localization/localization.component.ts
> +export class AppModule {}`;
Is this used anywhere? 🤔

2024-12-04 10:17 UTC, RasmusKjeldgaard commented on apps/cookbook/src/app/localization/localization.component.ts
> +export class AppModule {}`;
Thanks for catching this! Added it to the docs page now.

2024-12-04 12:27 UTC, jakobe approved these changes

2024-12-04 12:28 UTC, Fuzzy3 approved these changes

2024-12-04 12:28 UTC, merged

2024-12-04 19:08 UTC, MortenGregersen commented
Great to finally get the issue closed 🎉

2024-12-04 21:35 UTC, RasmusKjeldgaard commented
> Great to finally get the issue closed 🎉

Hi @MortenGregersen 👋 Nice to see you around here again 😄 

Before it was closed, #942 was the second-oldest open issue on our backlog. Only outlived by https://github.com/kirbydesign/designsystem/issues/803.