Bug/3680 error message not announced
kirbydesign/designsystem pull request #3746
Opened 2024-12-20 10:04 UTC by RasmusKjeldgaard

## Which issue does this PR close?

This PR closes # (insert issue number here)

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any additional context?

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

2025-01-16 14:55 UTC, RasmusKjeldgaard commented on libs/designsystem/form-field/src/form-field.component.ts
> -    // https://github.com/ionic-team/ionic-framework/issues/22740
Checking for the readOnly property complicates the logic a bit as the `nestedInteractiveElement` can now also be a radio-group that does not have that property.

The linked issue is fixed by Ionic, so instead I tried to be a good scout and removed the logic.

I tested on a device, and inputs with readOnly cannot be focussed, while inputs without can be focussed with a single click as expected.

2025-01-20 11:40 UTC, Fuzzy3 requested changes

2025-01-20 11:40 UTC, Fuzzy3 commented on libs/designsystem/form-field/src/form-field.component.ts
> +  @Input() get message(): string | null {
No need for getter/setter on Input if there are no side effects in any of the functions

2025-01-20 11:40 UTC, Fuzzy3 commented on libs/designsystem/form-field/src/form-field.component.ts
> +  private setNestedInteractiveElementAttributes() {
Call this from setter on message

2025-01-20 11:40 UTC, Fuzzy3 commented on libs/designsystem/form-field/src/form-field.component.ts
> +  private setNestedInteractiveElementAttributes() {
Read-up on the angular life-cycle to determine when the initialization and setting of element attributes should happen. (Does it make sense to have both "afterContentChecked" and "afterContentInit")

2025-01-20 11:40 UTC, Fuzzy3 commented on libs/designsystem/form-field/src/form-field.component.ts
> +    this._nestedInteractiveHasError = nestedInteractiveComponent?.hasError;
Convert to boolean in the case that hasError does not exist on nestedInteractiveComponent (in the case that a new component has been added to the list of components that can be used in a formfield)
```suggestion
    this._nestedInteractiveHasError = !!nestedInteractiveComponent?.hasError;
```

2025-01-20 11:40 UTC, Fuzzy3 commented on libs/designsystem/form-field/src/form-field.component.ts
> +    this.nestedInteractiveErrorSubscription = nestedInteractiveComponent?.hasErrorChange.subscribe(
Add question mark if hasErrorChange is not defined in nestedInteractiveComponent
```suggestion
    this.nestedInteractiveErrorSubscription = nestedInteractiveComponent?.hasErrorChange?.subscribe(
```

2025-01-20 11:40 UTC, Fuzzy3 commented on libs/designsystem/form-field/src/form-field.component.ts
> +    const nestedInteractiveComponent =
Should we consider having an interface for all supported nestedInteractiveComponents to make sure they all implement "hasError" and "hasErrorChange"?

2025-01-31 10:01 UTC, RasmusKjeldgaard commented on libs/designsystem/form-field/src/form-field.component.ts
> +    this.nestedInteractiveErrorSubscription = nestedInteractiveComponent?.hasErrorChange.subscribe(
The nestedInteractiveComponent is strongly typed due to this line above:
```
const nestedInteractiveComponent =
      this.inputComponent || this.textareaComponent || this.radioGroupComponent;
```

2025-01-31 12:56 UTC, RasmusKjeldgaard commented on libs/designsystem/form-field/src/form-field.component.ts
> +    const nestedInteractiveComponent =
Good idea!

2025-01-31 12:57 UTC, RasmusKjeldgaard commented on libs/designsystem/form-field/src/form-field.component.ts
> +  private setNestedInteractiveElementAttributes() {
Good call, I've refactored it a bit to avoid duplicating stuff into the`AfterContentInit` hook.

2025-02-05 14:52 UTC, Fuzzy3 approved these changes, later dismissed
Really nice job ! Just a single suggestion to make a base class for the formfieldcontrol. However i'm approving since that might be out of scope

2025-02-05 14:52 UTC, Fuzzy3 commented on libs/designsystem/types/src/form-field-control.ts
> +export interface FormFieldControl {
I ❤️ this

2025-02-05 14:52 UTC, Fuzzy3 commented on libs/designsystem/types/src/form-field-control.ts
> +export interface FormFieldControl {
Now that I'm looking at the hasError logic, I noticed its all the same lines of code. Maybe we should have a base FormFieldControl that all the other components extend?

2025-02-07 08:23 UTC, RasmusKjeldgaard commented on libs/designsystem/types/src/form-field-control.ts
> +export interface FormFieldControl {
Good idea, would prefer if we add it in another PR for just that 🚀

2025-02-07 08:46 UTC, Fuzzy3 approved these changes

2025-02-07 08:46 UTC, merged